name: Build 30 - MacOS x86_64
on: workflow_dispatch
jobs:
  wheels-macos:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
#    - name: Install Zlib
#      run: |
#        brew install zlib
    - name: Install Eigen
      run: |
        brew install eigen
    - name: Install Swig
      run: |
        brew install swig
        swig -version
    - name: Install Boost
      run: |
        brew install boost
        cd /usr/local/lib
    - name: Build ORE
      run: |
        pwd
        tar xfz ore.tgz
        #cp exchangerate.hpp ore/QuantLib/ql
        #tar xfz oreswig.tgz
        #cp setup.py oreswig/OREAnalytics-SWIG/Python/setup.py
        python -m pip install setuptools
        cp oreanalytics-config.macos ore/ORE-SWIG/oreanalytics-config
        cd ore
        mkdir build
        cd build
        cmake -DORE_USE_ZLIB=ON -DORE_BUILD_DOC=OFF -DORE_BUILD_EXAMPLES=OFF -DORE_BUILD_SWIG=OFF -DORE_BUILD_TESTS=OFF -DORE_BUILD_APP=OFF -DQL_BUILD_BENCHMARK=OFF -DQL_BUILD_EXAMPLES=OFF -DQL_BUILD_TEST_SUITE=OFF -DQL_ENABLE_SESSIONS=ON -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . -j4
        cmake --install .
        cd ..
        cd ORE-SWIG
        python setup.py wrap
    - name: Build ORE wheels
      uses: pypa/cibuildwheel@v2.22.0
      env:
        CIBW_SKIP: cp36-* cp37-*
        #CIBW_BUILD: cp310-macosx_x86_64
        #CIBW_BUILD: cp311-macosx_x86_64
        CIBW_ARCHS_MACOS: x86_64
        CXXFLAGS: -std=c++17 -g0 -O3 -mmacosx-version-min=13.7
        CIBW_BUILD_VERBOSITY: 2
        CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
          DYLD_LIBRARY_PATH=/usr/local/lib delocate-listdeps {wheel} &&
          DYLD_LIBRARY_PATH=/usr/local/lib delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}
      with:
        package-dir: ore/ORE-SWIG
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheels-macos-x86_64
        path: ./wheelhouse/*.whl
